### PR TITLE
Added image to 2nd article like in original

### PR DESCRIPTION
**Pull request by hugo007test**
Look, in the original article there is an image in the beginning. I do not know, maybe you don't want or just forget about it. But, I propose to fix it.

### CODE REVIEW

**Comment by ruig1992** [comment]
No, I didn't. :smirk:  I just decided to cut a little space in the article. I do not think that this image is so important.

**Comment by hugo007test** [comment]
:worried:  You are right in something. But, I think that a little illustration will not hurt - the article will not consist only of text. Moreover, there is a picture of the situation in question - relations in the team.

**Comment by ruig1992** [comment]
You know, I was thinking ... The article really does not have enough images. I will accept your changes. :blush:

**Comment by ruig1992** [comment]
Done. Thanks!

**Pull request merged**
